### ISSUE TITLE
Automate token transformation

### ISSUE THREAD

**Issue by kendrick** [compassion-gds/compassion-gds#123]
A [GitHub Action](https://github.com/compassion-global-experience/cds-tokens/actions/workflows/transform-tokens.yml) performs a **very** rudimentary transform of our design tokens and commits the output to the repo. How can we make this better?

**Comment by kidroca** [comment]
We've changed the process so that tokens and CSS variables are generated as part of the build process

We don't need to automate this further because:
- local developers would run the `build` as part of the `dev` script (therefore have the latest tokens)
- releasing the package would also include the build step
